### ISSUE TITLE
custom.css

### ISSUE THREAD

**Issue by jkobject** [gaerfield/reveal-md-github-pages#1]
Hey I just tried your tool.

It is awesome. However it seems that the custom.css file is not loaded (even in your example).

Maybe changing the path?

Best,

**Comment by gaerfield** [comment]
Oh man sry... Thanks for the bug report. I haven't realized I have one until I tried to use template myself today. The path wasn't wrong, it's simply github-pages ignoring directories starting with underscores (except if a `.nojekyll` file exists). Wouldn't got it without you. Appreciations :heart:.
I [fixed the github build pipeline](https://github.com/gaerfield/reveal-md-github-pages/commit/c4172d36898d40d0ec113ce944297963424f752e). Should work fine now.

**Comment by gaerfield** [comment]
Fixed in c4172d36898d40d0ec113ce944297963424f752e
